export const CITY_PALETTE = Object.freeze({
  sky: 0x1a0f10,
  fog: 0x241517,
  stone: 0xc8a370,
  stoneEdge: 0x765332,
  street: 0x2a2021,
  earth: 0x130c0d,
  bronze: 0x65452f,
  iron: 0x1b2221,
  patina: 0x2c6d67,
  water: 0x285f65,
  amber: 0xf0b45f,
  teal: 0x5bd2c6,
  wine: 0x71352f,
});

export const MODEL_ROOT = '/assets/chapter03-3d/models';

export const CITY_MODELS = Object.freeze([
  {
    id: 'archive',
    label: 'Old Municipal Archive',
    file: 'old_municipal_archive_web.glb',
    position: [-18, 0, -15.2],
    rotationY: 0,
    scale: 1,
  },
  {
    id: 'transit-ministry',
    label: 'Transit Ministry',
    file: 'transit_ministry_web.glb',
    position: [30.2, 0, -7],
    rotationY: 0,
    scale: 1,
  },
  {
    id: 'scanner-tower',
    label: 'Scanner Tower',
    file: 'scanner_tower_web.glb',
    position: [12.6, 0, -12],
    rotationY: 125,
    scale: 1,
  },
  {
    id: 'clock-tower',
    label: 'Central Clock',
    file: 'clock_tower_web.glb',
    position: [0, 0.34, 0],
    rotationY: -45,
    scale: 1.95,
  },
  {
    id: 'reunion-fountain',
    label: 'Reunion Fountain',
    file: 'reunion_fountain_web.glb',
    position: [20, 0.18, 0],
    rotationY: 0,
    scale: 1.12,
  },
  {
    id: 'municipal-tram',
    label: 'Municipal Tram',
    file: 'municipal_tram_web.glb',
    position: [0, 0, 24.5],
    rotationY: -90,
    scale: 1,
  },
  {
    id: 'market-stall-west',
    label: 'Produce Market',
    file: 'produce_market_stall_web.glb',
    position: [-20, 0, 3.5],
    rotationY: 0,
    scale: 1.12,
  },
  {
    id: 'market-stall-east',
    label: 'Produce Market',
    file: 'produce_market_stall_web.glb',
    position: [-20, 0, -3.5],
    rotationY: -180,
    scale: 1.12,
    cloneOf: 'market-stall-west',
  },
  {
    id: 'queue-dispenser',
    label: 'Municipal Queue Dispenser',
    role: 'arrival ticket ritual',
    category: 'prop',
    file: 'ch03_queue_dispenser.glb',
    position: [-6.8, 0.5, 18.3],
    rotationY: 0,
    scale: 1.9,
    alignToGround: true,
    collision: { type: 'circle', radius: 0.9 },
  },
  {
    id: 'produce-scale',
    label: 'Eda\'s Produce Scale',
    role: 'market weight routine',
    category: 'prop',
    file: 'ch03_produce_scale.glb',
    position: [-13.2, 0.5, 4.1],
    rotationY: 32,
    scale: 1.5,
    alignToGround: true,
    collision: { type: 'circle', radius: 1 },
  },
  {
    id: 'porter-handcart',
    label: 'Porter Handcart',
    role: 'repeatable porter route',
    category: 'prop',
    file: 'ch03_porter_handcart.glb',
    position: [-24.2, 0.5, -1.4],
    rotationY: -24,
    scale: 2.2,
    alignToGround: true,
    collision: { type: 'box', size: [2.8, 1.65] },
  },
  {
    id: 'receipt-device',
    label: 'Receipt Roll and Spike',
    role: 'duplicate receipt evidence',
    category: 'prop',
    file: 'ch03_receipt_spike.glb',
    position: [-11.3, 0.5, -4.4],
    rotationY: 68,
    scale: 1.08,
    alignToGround: true,
    collision: { type: 'circle', radius: 0.72 },
  },
  {
    id: 'queue-stanchion',
    label: 'Queue Stanchion',
    role: 'bureaucratic queue boundary',
    category: 'prop',
    file: 'ch03_queue_stanchion.glb',
    position: [-5.8, 0.5, -11.1],
    rotationY: -18,
    scale: 1.7,
    alignToGround: true,
    collision: { type: 'box', size: [1.75, 0.8] },
  },
  {
    id: 'clerk-stamp-machine',
    label: 'Clerk Sava\'s Stamp Machine',
    role: 'duplicate-pass bureaucracy',
    category: 'prop',
    file: 'ch03_clerk_stamp_machine.glb',
    position: [-5.2, 1.34, -19.5],
    rotationY: 18,
    scale: 1.08,
    alignToGround: true,
    support: { type: 'counter', size: [1.65, 0.82, 1.1] },
    collision: { type: 'box', size: [1.75, 1.2] },
  },
  {
    id: 'crosswalk-signal',
    label: 'Civic Crosswalk Signal',
    role: 'traffic-pattern rehearsal',
    category: 'prop',
    file: 'ch03_crosswalk_signal.glb',
    position: [9.2, 0.5, -8.8],
    rotationY: 14,
    scale: 2.45,
    alignToGround: true,
    collision: { type: 'circle', radius: 0.48 },
  },
  {
    id: 'fountain-bench',
    label: 'Reunion Bench',
    role: 'Mara conversation anchor',
    category: 'prop',
    file: 'ch03_fountain_bench.glb',
    position: [20, 0.5, 8.2],
    rotationY: 0,
    scale: 2.75,
    alignToGround: true,
    collision: { type: 'box', size: [3.25, 1.15] },
  },
  {
    id: 'pa-speaker',
    label: 'Lockdown PA Speaker',
    role: 'civic countdown voice',
    category: 'prop',
    file: 'ch03_pa_speaker.glb',
    position: [8.5, 4.65, -19.2],
    rotationY: -145,
    scale: 1.18,
    alignToGround: true,
    support: { type: 'pole', height: 4.1 },
  },
  {
    id: 'night-ticket-reader',
    label: 'Night Train Ticket Reader',
    role: 'two-ticket boarding test',
    category: 'prop',
    file: 'ch03_night_ticket_reader.glb',
    position: [5.9, 0.5, 16.1],
    rotationY: -28,
    scale: 1.9,
    alignToGround: true,
    collision: { type: 'circle', radius: 0.96 },
  },
]);

export const COURTS = Object.freeze([
  { id: 'arrival', center: [0, 16.25], size: [21, 12.5], shape: 'box' },
  { id: 'market', center: [-17.25, 0.25], size: [19.5, 22.5], shape: 'box' },
  { id: 'clock', center: [0, 0], radius: 13.2, shape: 'octagon' },
  { id: 'transit', center: [2, -15.25], size: [23, 15.5], shape: 'box' },
  { id: 'fountain', center: [20.25, 0], radius: 10.8, shape: 'octagon' },
]);

export const WORLD_NODES = Object.freeze({
  c_n: [0, -7], c_ne: [5, -5], c_e: [7, 0], c_se: [5, 5],
  c_s: [0, 7], c_sw: [-5, 5], c_w: [-7, 0], c_nw: [-5, -5],
  t_door: [0, 17], t_plat: [0, 13.5], t_sw: [-6.5, 13],
  m_entry: [-12, 9.5], m_plaza: [-16, 4.5], m_group: [-15.8, 7.2],
  m_stalls: [-19.5, 0], m_east: [-15, -0.5], m_gateE: [-10.5, -0.5],
  m_north: [-16, -5], tr_s: [0, -10], tr_bus: [-2.5, -17.5],
  tr_e: [4, -14.5], tr_ne: [8, -12.5], f_nw: [14.8, -5.5],
  f_n: [20, -6.5], f_ne: [24.5, -3], f_pad: [25.4, 1.2],
  f_bell: [23.6, 4.6], f_s: [20, 6.5], f_mark: [15.2, 5],
  f_w: [13.8, 0.5],
});

export const WORLD_EDGES = Object.freeze([
  ['c_n', 'c_ne'], ['c_ne', 'c_e'], ['c_e', 'c_se'], ['c_se', 'c_s'],
  ['c_s', 'c_sw'], ['c_sw', 'c_w'], ['c_w', 'c_nw'], ['c_nw', 'c_n'],
  ['t_door', 't_plat'], ['t_plat', 't_sw'], ['t_sw', 'm_entry'],
  ['m_entry', 'm_plaza'], ['m_plaza', 'm_group'], ['m_plaza', 'm_stalls'],
  ['m_stalls', 'm_north'], ['m_stalls', 'm_east'], ['m_east', 'm_group'],
  ['m_east', 'm_gateE'], ['m_gateE', 'c_w'], ['c_n', 'tr_s'],
  ['tr_s', 'tr_bus'], ['tr_s', 'tr_e'], ['tr_bus', 'tr_e'], ['tr_e', 'tr_ne'],
  ['tr_ne', 'f_nw'], ['f_nw', 'f_n'], ['f_n', 'f_ne'], ['f_ne', 'f_pad'],
  ['f_pad', 'f_bell'], ['f_bell', 'f_s'], ['f_s', 'f_mark'],
  ['f_mark', 'f_w'], ['f_w', 'f_nw'],
]);

export const OBSTACLES = Object.freeze([
  { type: 'circle', center: [0, 0], radius: 4.9 },
  { type: 'circle', center: [20, 0], radius: 4.7 },
  { type: 'circle', center: [12.6, -12], radius: 1.75 },
  { type: 'box', center: [-20, 3.5], size: [4.6, 3.4] },
  { type: 'box', center: [-20, -3.5], size: [4.6, 3.4] },
]);

export const CAMERA_HOME = Object.freeze({
  position: [52, 82, 52],
  target: [1.5, 0.8, 0],
  zoom: 1.14,
});

export const CAMERA_FOCUS_TARGETS = Object.freeze({
  arrival: [0, 0.8, 16],
  market: [-17, 0.8, 0],
  transit: [2, 0.8, -15],
  fountain: [20, 0.8, 0],
});
